apiVersion: v1
kind: Namespace
metadata:
  name: infisical-operator-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config
  namespace: infisical-operator-system
data:
  hostAPI: "https://example.com/api"
  tls.caRef.secretName: custom-ca-certificate
  tls.caRef.secretNamespace: default
  tls.caRef.key: ca.crt